### ISSUE TITLE
iplists.firehol.org

### ISSUE THREAD

**Issue by ktsaou** [eSentire/malfeed#1]
Hi,

I maintain http://iplists.firehol.org.

A user suggested adding your feeds: http://iplists.firehol.org/?ipset=firehol_level1#comment-2645900749

Should I add one feed on iplists.firehol.org for each of the files you have in this repo, or should I group them somehow?

Is it possible to have just a line of description for each of them?

Thanks!

**Comment by r0yfire** [comment]
You should use the `index.txt` file as your starting point.
Here's an example how [Cymon.io](https://cymon.io) parses it:

``` python
class IngestEsentireMalfeed(BaseNexusModule):

    def __init__(self):
        self.base_url = "https://raw.githubusercontent.com/eSentire/malfeed/master"
        self.source_name = "eSentire Threat Labs"
        self.reports = {}


    def run(self):
        for report in self.get_index():
            self.log("%s ingesting %s" %(self.__class__.__name__, report['file']))
            content = self.get_url(self.base_url + '/' + report['file'])
            domain = report['file'].replace('_watch_ip.lst', '')
            for ip in content.split('\n'):
                ip = ip.strip()
                if len(ip) > 1:
                    # create event
                    event = {
                        "ip": ip,
                        "domain": domain,
                        "details_url": "https://github.com/eSentire/malfeed",
                        "description": "Domain: %s" %(domain),
                        "source": self.source_name,
                        "event_name": report['event_name'],
                        "event_title": "%s reported by %s" %(report['event_name'].lower().capitalize(), self.source_name),
                        "validation_hash": self.hash(ip + domain + report['event_name'] + self.source_name)
                    }
                    if report['description']:
                        event['description'] = report['description']
                    if report['details_url']:
                        event['details_url'] = report['details_url']

                    # add events to reports dictionary
                    if self.reports.has_key(event['ip']):
                        self.reports[event['ip']].append(event)
                    else:
                        self.reports[event['ip']] = [event]

    def get_index(self):
        index = []
        content = self.get_url(self.base_url + '/index.txt')
        for row in csv.reader(content.split('\n')):
            if len(row) > 1:
                report = {"file":  row[0], "event_name": row[1].lower(), 'details_url': None, 'description': None}
                if len(row) > 2 and len(row[2]) > 0:
                    report['description'] = row[2]
                if len(row) > 3 and len(row[3]) > 0 and 'http' in row[3]:
                    report['details_url'] = row[3]
                index.append(report)
        return index
```

Alternatively, you can also try using the [Cymon APIs](http://docs.cymon.io)

**Comment by ktsaou** [comment]
Thanks! Added them:

http://iplists.firehol.org/?ipset=esentire_auth_update_ru
http://iplists.firehol.org/?ipset=esentire_crazyerror_su
http://iplists.firehol.org/?ipset=esentire_differentia_ru
http://iplists.firehol.org/?ipset=esentire_dorttlokolrt_com
http://iplists.firehol.org/?ipset=esentire_downs1_ru
http://iplists.firehol.org/?ipset=esentire_emptyarray_ru
http://iplists.firehol.org/?ipset=esentire_krnqlwlplttc_com
http://iplists.firehol.org/?ipset=esentire_maddox1_ru
http://iplists.firehol.org/?ipset=esentire_manning1_ru
http://iplists.firehol.org/?ipset=esentire_smartfoodsglutenfree_kz
http://iplists.firehol.org/?ipset=esentire_atomictrivia_ru
http://iplists.firehol.org/?ipset=esentire_disorderstatus_ru
http://iplists.firehol.org/?ipset=esentire_22072014a_com
http://iplists.firehol.org/?ipset=esentire_14072015_com
http://iplists.firehol.org/?ipset=esentire_14072015q_com
http://iplists.firehol.org/?ipset=esentire_22072014b_com
http://iplists.firehol.org/?ipset=esentire_22072014c_com
http://iplists.firehol.org/?ipset=esentire_volaya_ru
http://iplists.firehol.org/?ipset=esentire_dagestanskiiviskis_ru
http://iplists.firehol.org/?ipset=esentire_islamislamdi_ru
http://iplists.firehol.org/?ipset=esentire_hasanhashsde_ru
http://iplists.firehol.org/?ipset=esentire_venerologvasan93_ru
http://iplists.firehol.org/?ipset=esentire_ebankoalalusys_ru
http://iplists.firehol.org/?ipset=esentire_mysebstarion_ru
http://iplists.firehol.org/?ipset=esentire_misteryherson_ru
http://iplists.firehol.org/?ipset=esentire_inleet_ru
http://iplists.firehol.org/?ipset=esentire_atomictrivia_ru
http://iplists.firehol.org/?ipset=esentire_fioartd_com
http://iplists.firehol.org/?ipset=esentire_getarohirodrons_com

Keep in mind atomictrivia.ru is twice in the index file.

**Comment by ktsaou** [comment]
And the code in BASH:

https://github.com/firehol/firehol/blob/c72d6c8a9ceb6a46f73c4cb29cada8034a28d979/sbin/update-ipsets.in#L3826-L3877
